DROP SCHEMA IF EXISTS FIGHTDB; 

CREATE DATABASE FIGHTDB
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE FIGHTDB.USER
(
uid int NOT NULL AUTO_INCREMENT,
exp int NOT NULL,
avatar int NOT NULL DEFAULT 0,
username char(20) NOT NULL,
passwd char(32) NOT NULL,
firstname char(30),
lastname char(30),
email char(50),
CONSTRAINT pk_uid PRIMARY KEY (uid)
);

CREATE TABLE FIGHTDB.FRIEND
(
frid int NOT NULL AUTO_INCREMENT,
uid int NOT NULL,
fuid int NOT NULL,
CONSTRAINT pk_frid PRIMARY KEY (frid)
);

CREATE TABLE FIGHTDB.T_GROUP
(
tgid int NOT NULL AUTO_INCREMENT,
uid int NOT NULL,
title char(40) NOT NULL,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
priority int DEFAULT 0 NOT NULL,
CONSTRAINT pk_t_gid PRIMARY KEY (tgid),
CONSTRAINT fk_t_uid FOREIGN KEY (uid) REFERENCES FIGHTDB.USER(uid) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FIGHTDB.TASK
(
tid int NOT NULL AUTO_INCREMENT,
uid int NOT NULL,
otid int NOT NULL DEFAULT 0,
tgid int NOT NULL,
content char(140),
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
isdone BOOLEAN DEFAULT FALSE,
privacy int NOT NULL DEFAULT 0,
CONSTRAINT pk_otask_tid PRIMARY KEY (tid),
CONSTRAINT fk_otask_uid FOREIGN KEY (uid) REFERENCES FIGHTDB.USER(uid) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_otask_tgid FOREIGN KEY (tgid) REFERENCES FIGHTDB.T_GROUP(tgid) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE FIGHTDB.EXP
(
expid int NOT NULL AUTO_INCREMENT,
uid int NOT NULL,
tid int NOT NULL,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
CONSTRAINT pk_expid PRIMARY KEY (expid),
CONSTRAINT fk_exp_uid FOREIGN KEY (uid) REFERENCES FIGHTDB.USER(uid) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_exp_tid FOREIGN KEY (tid) REFERENCES FIGHTDB.TASK(tid) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO FIGHTDB.USER (username, passwd, firstname, lastname, email) VALUES('plutoless', MD5('test'), 'Qianze', 'Zhang', 'qz@gmail.com');
INSERT INTO FIGHTDB.USER (username, passwd, firstname, lastname, email) VALUES('cashsun', MD5('test'), 'Cash', 'Sun', 'cs@gmail.com');

INSERT INTO FIGHTDB.T_GROUP (uid, title) VALUES('1', 'game');
INSERT INTO FIGHTDB.T_GROUP (uid, title) VALUES('1', 'IT');
INSERT INTO FIGHTDB.T_GROUP (uid, title) VALUES('2', 'daily');

INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('1','1','2', 'IT CONTENT');
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('1','2','2', 'IT CONTENT2');
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('1','3','2', 'IT CONTENT3');
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('1','4','1', 'GAME CONTENT');
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('1','5','1', 'GAME CONTENT2');
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('1','6','1', 'GAME CONTENT3');
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('2','7','3', 'DAILY CONTENT');
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('2','8','3', 'DAILY CONTENT2');
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('2','9','3', 'DAILY CONTENT3');

/* REPO */
INSERT INTO FIGHTDB.TASK (uid, otid, tgid, content) VALUES('2','5','3', 'DAILY CONTENT3');

INSERT INTO FIGHTDB.FRIEND (uid, fuid) VALUES('1','2');
